DROP DATABASE IF EXISTS bookstore;
CREATE DATABASE bookstore;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(250) UNIQUE NOT NULL,
  pasword VARCHAR(250) NOT NULL,
  role_id INTEGER REFERENCES roles(id)
);

DROP TABLE IF EXISTS books;
CREATE TABLE books (
  id SERIAL PRIMARY KEY,
  title VARCHAR(250) UNIQUE NOT NULL,
  author_id INTEGER REFERENCES authors(id),
  genre_id INTEGER REFERENCES genres(id),
  image VARCHAR(1000) NOT NULL
);

DROP TABLE IF EXISTS authors;
CREATE TABLE authors (
  id SERIAL PRIMARY KEY,
  name VARCHAR(250) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS genres;
CREATE TABLE genres (
  id SERIAL PRIMARY KEY,
  name VARCHAR(250) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS roles;
CREATE TABLE roles (
  id SERIAL PRIMARY KEY,
  name VARCHAR(250) UNIQUE NOT NULL
);
